# Generated by Django 3.0.6 on 2020-06-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200610_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='violence',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
